### PR TITLE
update docker version to 17.05

### PR DESCRIPTION
**Pull request by canghai908**
update docker version to 17.05 use multi-stage build

### CODE REVIEW

**Comment by lowzj** [comment]
Thanks for your contributing! We want to support different versions of docker as many as we can, so I will not merge this pull request.

**Comment by canghai908** [comment]
@lowzj  when I use build images on  docker  1.12.5 verson，the following error occurred。
`[INFO] --- docker-maven-plugin:1.0.0:build (default-cli) @ supernode ---
[INFO] Using authentication suppliers: [ConfigFileRegistryAuthSupplier]
[INFO] Copying /usr/src/Dragonfly/src/supernode/target/supernode.jar -> /usr/src/Dragonfly/src/supernode/target/docker/supernode.jar
[INFO] Copying /usr/src/Dragonfly/src/supernode/src/main/docker/sources/nginx.conf -> /usr/src/Dragonfly/src/supernode/target/docker/sources/nginx.conf
[INFO] Copying /usr/src/Dragonfly/src/supernode/src/main/docker/sources/start.sh -> /usr/src/Dragonfly/src/supernode/target/docker/sources/start.sh
[INFO] Copying /usr/src/Dragonfly/src/supernode/src/main/docker/Dockerfile -> /usr/src/Dragonfly/src/supernode/target/docker/Dockerfile
[INFO] Building image supernode:0.2.0
Step 1 : FROM busybox:latest as SRC
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.605 s
[INFO] Finished at: 2018-07-02T18:45:53+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:1.0.0:build (default-cli) on project supernode: Exception caught: Error parsing reference: "busybox:latest as SRC" is not a valid repository/tag -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
BUILD(supernode): FAILURE`

**Comment by zhouhaibing089** [comment]
There is a misunderstanding here:

The docker version specified in `docs/zh/install_server.md` is the version for running the application but what @canghai908 raised is about the version to build the application successfully.

**Comment by allencloud** [comment]
Thanks @canghai908 
Actually, we have not tested docker 17.05. In Alibaba, now we use [PouchContainer](https://github.com/alibaba/pouch).
And we encourage end-users could help test Dragonfly with PouchContainer or any version of Docker. Thanks.

**Comment by lowzj** [comment]
long time no feedback.
please reopen this pull request if continue.

**Pull request closed without merging**
